### PR TITLE
JL update Nov 18, 2020

### PR DESCRIPTION
**Pull request by jakelawlor**
Addressed outstanding issues. Main things: reformatted slides that were too big for slide area, reformatted order or some lessons, changed layers outline, checked spelling, grammar, and sentence structure.

### CODE REVIEW

**Comment by pedrohbraga** [comment]
Hi, @jakelawlor! Thank you for the pull request! Your pull request has failed and could not be deployed because of a missing package. Could you please fix this so your pull request can pass?

```
Quitting from lines 444-446 (workshop03-en.Rmd) 

Error in library(GGally) : there is no package called 'GGally'
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> library
```

**Comment by jakelawlor** [comment]
Hi @pedrohbraga - It's listed in the first qcbs intro slide, so I thought it would install automatically? I guess not. I added an install.package line before it's used to try again.

**Comment by pedrohbraga** [comment]
> Hi @pedrohbraga - It's listed in the first qcbs intro slide, so I thought it would install automatically? I guess not. I added an install.package line before it's used to try again.

Hi, again! Yes, I can see that it was listed within the first function. I do not know what is going on, but I have seen the [code](https://github.com/QCBSRworkshops/qcbsRworkshops/blob/master/R/first_slides.R) for the `first_slides()` function and, apparently, it does not install packages.

I will check this later on! I will wait for Travis CI to deploy your changes and see if it will pass!

**Review by mhBrice — APPROVED** [review]

**Comment by mhBrice** [comment]
I merged your PR, if you have more edits you can open a new PR

**Pull request merged**
